services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\WysiwygModule\Migration\Command\MigrateMediaUrlsToIdsCommand:
    tags:
      - { name: 'console.command', command: 'ddoewysiwyg:migrate:urls-to-ids' }

  OxidEsales\WysiwygModule\Migration\Service\FieldMigrationServiceInterface:
    class: OxidEsales\WysiwygModule\Migration\Service\FieldMigrationService

  OxidEsales\WysiwygModule\Migration\Service\MediaMigrationResultFilterInterface:
    class: OxidEsales\WysiwygModule\Migration\Service\MediaMigrationResultFilter

  OxidEsales\WysiwygModule\Migration\Service\MigrationServiceInterface:
    class: OxidEsales\WysiwygModule\Migration\Service\MediaIdAnchorMigrationService

  OxidEsales\WysiwygModule\Migration\Repository\FieldMigrationRepositoryInterface:
    class: OxidEsales\WysiwygModule\Migration\Repository\FieldMigrationRepository

  OxidEsales\WysiwygModule\Migration\Service\MediaIdAnchorMigrationService: ~

  OxidEsales\WysiwygModule\Migration\Command\MigrateMediaAltTextsCommand:
    tags:
      - { name: 'console.command', command: 'ddoewysiwyg:migrate:alt-texts' }

  OxidEsales\WysiwygModule\Migration\Repository\AltTextMigrationRepositoryInterface:
    class: OxidEsales\WysiwygModule\Migration\Repository\AltTextMigrationRepository

  OxidEsales\WysiwygModule\Migration\Service\AltTextMigrationServiceInterface:
    class: OxidEsales\WysiwygModule\Migration\Service\MediaAltTextMigrationService
  OxidEsales\WysiwygModule\Migration\Factory\MigrationReporterFactoryInterface:
    class: OxidEsales\WysiwygModule\Migration\Factory\MigrationReporterFactory
