services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\WysiwygModule\Migration\Command\MigrateMediaUrlsToIdsCommand:
    class: OxidEsales\WysiwygModule\Migration\Command\MigrateMediaUrlsToIdsCommand
    tags:
      - { name: 'console.command', command: 'ddoewysiwyg:migrate:urls-to-ids' }
    arguments:
      $fieldMigrationRepository: '@OxidEsales\WysiwygModule\Migration\Service\MediaIdAnchorMigrationRepository'

  OxidEsales\WysiwygModule\Migration\Service\MediaIdAnchorMigrationRepository:
    class: OxidEsales\WysiwygModule\Migration\Repository\FieldMigrationRepository
    arguments:
      $migrationService: '@OxidEsales\WysiwygModule\Migration\Service\MediaIdAnchorMigrationService'

  OxidEsales\WysiwygModule\Migration\Service\MediaIdAnchorMigrationService: ~

  OxidEsales\WysiwygModule\Migration\Service\MigrationReportInterface:
    class: OxidEsales\WysiwygModule\Migration\Service\MigrationReport

  OxidEsales\WysiwygModule\Migration\Service\MigrationReportCsvWriterInterface:
    class: OxidEsales\WysiwygModule\Migration\Service\MigrationReportCsvWriter