name: Trigger

on:
  pull_request:
  push:
    branches:
      - 'b-7.1.x*'

jobs:
  p81m80both:
    name: 'Php-8.1-Mysql-8.0'
    uses: ./.github/workflows/development.yml
    secrets: inherit
    with:
      php: '8.1'
      mysql: '8.0'
      report_sonarcloud: true